using pearlxcore.dev.Models.Entities;
using pearlxcore.dev.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Serilog;

namespace pearlxcore.dev.Areas.Admin.Controllers;

public class CategoriesController : AdminController
{
    private readonly ICategoryService _service;
    private readonly IAuditLogService _auditLogService;

    public CategoriesController(ICategoryService service, IAuditLogService auditLogService)
    {
        _service = service;
        _auditLogService = auditLogService;
    }

    public async Task<IActionResult> Index()
        => View(await _service.GetAllAsync());

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(string name)
    {
        if (!string.IsNullOrWhiteSpace(name))
        {
            var category = new Category
            {
                Name = name
                // Slug will be generated by the service
            };
            await _service.CreateAsync(category);
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _auditLogService.LogAsync("Create", "Category", category.Id, $"Created category: {category.Name}", userId);
            Log.Information("Category created by {User}: ID={CategoryId}, Name={Name}", User.Identity?.Name, category.Id, category.Name);
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var category = await _service.GetByIdAsync(id);
        if (category != null)
        {
            await _service.DeleteAsync(id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _auditLogService.LogAsync("Delete", "Category", id, $"Deleted category: {category.Name}", userId);
            Log.Information("Category deleted by {User}: ID={CategoryId}, Name={Name}", User.Identity?.Name, id, category.Name);
        }
        return RedirectToAction(nameof(Index));
    }
}
