using pearlxcore.dev.Models.Entities;
using pearlxcore.dev.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Serilog;

namespace pearlxcore.dev.Areas.Admin.Controllers;

public class TagsController : AdminController
{
    private readonly ITagService _service;
    private readonly IAuditLogService _auditLogService;

    public TagsController(ITagService service, IAuditLogService auditLogService)
    {
        _service = service;
        _auditLogService = auditLogService;
    }

    public async Task<IActionResult> Index()
        => View(await _service.GetAllAsync());

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(string name)
    {
        if (!string.IsNullOrWhiteSpace(name))
        {
            var tag = new Tag
            {
                Name = name
                // Slug will be generated by the service
            };
            await _service.CreateAsync(tag);
            
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _auditLogService.LogAsync("Create", "Tag", tag.Id, $"Created tag: {tag.Name}", userId);
            Log.Information("Tag created by {User}: ID={TagId}, Name={Name}", User.Identity?.Name, tag.Id, tag.Name);
        }

        return RedirectToAction(nameof(Index));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Delete(int id)
    {
        var tag = await _service.GetByIdAsync(id);
        if (tag != null)
        {
            await _service.DeleteAsync(id);
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            await _auditLogService.LogAsync("Delete", "Tag", id, $"Deleted tag: {tag.Name}", userId);
            Log.Information("Tag deleted by {User}: ID={TagId}, Name={Name}", User.Identity?.Name, id, tag.Name);
        }
        return RedirectToAction(nameof(Index));
    }
}
